#!/bin/bash

# Find the correct ALSA volume control 
guess_volume_control() {
 # Check if there is a working DSP volume control
 dsptoolkit get-volume 2>/dev/null >/dev/null
 if [ $? == 0 ]; then
    MIXER_CONTROL=DSPVolume
    return
 fi

 # DAC+ and Amp2 use "Digital" 
 DIGITAL=`amixer scontrols | grep Digital`
 if [ "$DIGITAL" != "" ]; then
   MIXER_CONTROL=Digital
   return                                 
 fi  

 # There should be at least a Softvol control
 SOFTVOL=`amixer scontrols | grep Softvol`
 if [ "$SOFTVOL" != "" ]; then
   MIXER_CONTROL=Softvol
   return
 fi

 echo "Could not find ALSA volume control"
}

# Guess what card is installed"
guess_card() {
 DACPRO=`aplay -l | grep DAC+ | grep Pro`
 if [ "$DACPRO" != "" ]; then
   CARD="DAC+ Pro"
   return
 fi

 DAC=`aplay -l | grep DAC+`
 if [ "$DAC" != "" ]; then
   CARD="DAC+/Amp2"
    return
 fi

 CLKGEN=`i2cget -y 1 0x60 2 2>/dev/null`
 if [ "$CLKGEN" == "0x03" ]; then
    CARD="Beocreate 4 channel amplifier"
    return
 fi

 REG1=`dsptoolkit read-reg 0xf003` # expected 00 01
 REG2=`dsptoolkit read-reg 0xf402` # expected 00 01
 REG3=`dsptoolkit read-reg 0xc000` # expected 00 00
 if [ "$REG1$REG2$REG3" == "00 01 00 01 00 00 " ]; then
    CARD="DAC+ DSP"
    return
 fi
}

MIXER_CONTROL=""
CARD="unknown"

guess_volume_control
guess_card

echo "Applying settings: "
echo " Sound card: " $CARD
echo " ALSA mixer control: $MIXER_CONTROL"

